Refactor onboarding
nitzanpap/dispatcher pull request #1
Opened 2023-02-15 14:59 UTC by nitzanpap

Refactored onboarding and fixed java bug

2023-02-19 20:50 UTC, abenartz requested changes

2023-02-19 20:50 UTC, abenartz commented on lib/widgets/my_text_button.dart
> +class MyTextButton extends StatelessWidget {
Its better not to name a custom view as "My..." b/c you'll have a lot of custom widget and all will be yours;)
Is better to name it exactly what it is.. something like "TextButtonWithRightIcon"

2023-02-19 20:50 UTC, abenartz commented on lib/screens/onboarding_screen.dart
>      Text TitleText(BuildContext context) {
this is a function, not a class. Also, nicer to pass it a color and not a context.
Rename as function: "getTitleTextView(Color color)"

2023-02-19 20:50 UTC, abenartz commented on lib/screens/onboarding_screen.dart
> +    void moveToNextStep() {
You have 2 functions inside the build function?
A function should not declared inside another function

2023-02-19 20:50 UTC, abenartz commented on lib/screens/onboarding_screen.dart
> +    final currentStepData = Provider.of<OnboardingStepProvider>(context);
Always name property for what he is.
This case its:
final onboardingStepProvider = .....

2023-02-19 20:50 UTC, abenartz commented on lib/screens/onboarding_screen.dart
>        ),
Maybe we don't have to declare appbar in this screen?

2023-02-19 20:50 UTC, abenartz commented on lib/screens/onboarding_screen.dart
> +const GAP = const Gap(GAP_SEPARATOR_HEIGHT);
Don't define const widget out of class scope.
Let's talk about it

2023-02-19 20:50 UTC, abenartz commented on lib/screens/onboarding_screen.dart
>                      child: Row(
We need to give DoublePaper more descriptive name. 
Also, is this should be stateful widget?

2023-02-19 20:50 UTC, abenartz commented on lib/main.dart
> +          create: (context) => OnboardingStepProvider(),
Should all the app need to use OnboardingStepProvider or only the the onboarding screen? We don't need this object instance will live all the app lifecycle.
What can we do about it?

2023-02-20 13:57 UTC, nitzanpap commented on lib/main.dart
> +          create: (context) => OnboardingStepProvider(),
Done.
Moved this provider to its relevant scope.

2023-02-20 14:11 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
>                      child: Row(
@abenartz Done.
Renamed all 'paper' widgets and refactored them into Stateless Widgets.

2023-02-20 14:12 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
> +const GAP = const Gap(GAP_SEPARATOR_HEIGHT);
@abenartz Done.
Moved these into the class's scope.

2023-02-20 14:15 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
> +    void moveToNextStep() {
@abenartz Done.
Rewrote the data flow and implemented the relevant functions to the discussed format.

2023-02-21 10:12 UTC, abenartz requested changes

2023-02-21 10:12 UTC, abenartz commented on lib/providers/onboarding_step_provider.dart
> +  void moveoToNextStep() {
Naming is ok but we can describe better what the function does:
I would call it "incrementOnbordingStep()" since that what actually happen inside.

2023-02-21 10:12 UTC, abenartz commented on lib/screens/onboarding_screen.dart
> +      int currentStep, OnboardingStepProvider onboardingStepProvider) {
Here we can pass only the descriptions. We don't need all the provider.

2023-02-21 10:12 UTC, abenartz commented on lib/screens/onboarding_screen.dart
> +                skipButton(),
Since it is a function: describe what the action the function does and what she returns:
"getSkipButtonView()",
"getNextButtonView()"

2023-02-21 10:12 UTC, abenartz commented on lib/screens/onboarding_screen.dart
> +  void skipOnboarding() {
"onSkipOnbordingPressed()"

2023-02-21 10:39 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
> +      backgroundColor: FigmaColors.deepDarkBlue,
@abenartz Done.

2023-02-21 10:39 UTC, nitzanpap commented on lib/global_constants.dart
> +class FigmaColors {
@abenartz Done.

2023-02-21 10:48 UTC, nitzanpap commented on lib/global_constants.dart
> +enum IconDirection {
@abenartz Done.

2023-02-21 10:48 UTC, nitzanpap commented on lib/providers/onboarding_step_provider.dart
> +  void moveoToNextStep() {
@abenartz Done.

2023-02-21 10:48 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
> +      int currentStep, OnboardingStepProvider onboardingStepProvider) {
@abenartz Done.

2023-02-21 10:48 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
> +                skipButton(),
@abenartz Done.

2023-02-21 10:48 UTC, nitzanpap commented on lib/screens/onboarding_screen.dart
> +  void skipOnboarding() {
@abenartz Done.

2023-02-21 13:08 UTC, abenartz commented on lib/global_constants.dart
> +class FigmaColors {
@nitzanpap 
Change the name of the constant_var file to "Strings"

2023-02-21 13:36 UTC, nitzanpap commented on lib/global_constants.dart
> +class FigmaColors {
@abenartz Done.

2023-02-21 15:33 UTC, abenartz approved these changes

2023-02-21 15:41 UTC, merged