Task2 Signup & Login Page
nitzanpap/dispatcher pull request #2
Opened 2023-02-25 11:38 UTC by nitzanpap

Task2: Added the Signup & Login Page

2023-02-27 17:00 UTC, abenartz requested changes

2023-02-27 17:00 UTC, abenartz commented on lib/widgets/input_field_widgets/email_input_field.dart
> +      hintText: 'john@gmail.com',
We don't use some demo email for hint just use 'Email' as the hint

2023-02-27 17:00 UTC, abenartz commented on lib/widgets/input_field_widgets/password_input_field.dart
> +  String? reEnteredPasswordValidator(reEnteredPassword) {
Name doesn't reveal what the func is doing and what return

2023-02-27 17:00 UTC, abenartz commented on lib/widgets/signup_login_form.dart
> +  void updateProvider({
This function should be in the provider and not in the widget.
You can create inside the provider function called logister(email, password).
Inside the provider we will pass the params to firebase.

Next lesson we will talk about our architecture design.

2023-02-28 09:59 UTC, nitzanpap commented on lib/widgets/signup_login_form.dart
> +  void updateProvider({
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/widgets/signup_login_form.dart
> +    return;
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/widgets/input_field_widgets/password_input_field.dart
> +  String? reEnteredPasswordValidator(reEnteredPassword) {
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/widgets/input_field_widgets/email_input_field.dart
> +      hintText: 'john@gmail.com',
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/widgets/button_widgets/primary_button.dart
> +  // final Color color;
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/helper_functions/validations.dart
> +    // Valid password
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/helper_functions/validations.dart
> +  // Returns null if the given string is a valid email, otherwise returns an informative message.
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/helper_functions/validations.dart
> +  static String? passwordValidator(String? value) {
@abenartz Done.

2023-02-28 09:59 UTC, nitzanpap commented on lib/helper_functions/validations.dart
> +  // Returns null if the given string is a valid password, otherwise returns an informative message.
@abenartz Done.

2023-02-28 10:00 UTC, nitzanpap commented on lib/helper_functions/validations.dart
> +  static String? emailValidator(String? value) {
@abenartz Done.

2023-02-28 10:03 UTC, nitzanpap commented on lib/screens/signup_login_screen.dart
> +    const logoLayered = LogoLayered();
@abenartz Done.

2023-02-28 18:16 UTC, abenartz approved these changes

2023-02-28 19:06 UTC, merged