Task3 firebase auth
nitzanpap/dispatcher pull request #3
Opened 2023-03-01 16:19 UTC by nitzanpap

2023-03-01 16:52 UTC, nitzanpap commented
"flutter run --dart-define-from-file=config_dev.json" - to run on the development environment.
"flutter run --dart-define-from-file=config_prod.json" - to run on the production environment

2023-03-05 10:13 UTC, abenartz requested changes

2023-03-05 10:13 UTC, abenartz commented on lib/widgets/signup_login_form.dart
> +  Future<String> submitForm({
1. Name isn't describe what the function does.
2. Too many actions for one function (registration and getting result msg)
3. All those actions are not UI related. What can we do? lets talk about it.

2023-03-05 10:13 UTC, abenartz commented on lib/widgets/signup_login_form.dart
> +            ScaffoldMessenger.of(context).clearSnackBars();
Those two lines comes a lot together. Consider global static function for showing snackbar.

2023-03-06 12:40 UTC, nitzanpap commented on lib/constants/firebase_auth_types.dart
> +abstract class FirebaseAuthResponseTypes {
@abenartz Done.

2023-03-06 12:41 UTC, nitzanpap commented on lib/widgets/signup_login_form.dart
> +  Future<String> submitForm({
@abenartz Done.
Changed the function name to 'getMessageFromFirebaseAuth', and moved it into the provider.

2023-03-06 12:44 UTC, nitzanpap commented on lib/widgets/signup_login_form.dart
> +            ScaffoldMessenger.of(context).clearSnackBars();
@abenartz Done.
Extracted these lines into a method of this class, since I don't know yet where I will use it again.
I will lift this method if it will be needed.

2023-03-06 12:46 UTC, nitzanpap commented on lib/constants/firebase_auth_types.dart
> +abstract class FirebaseAuthResponseTypes {
I have removed this abstract class as a whole and refactored it so it will only be relevant to the business logic.

2023-03-06 17:21 UTC, abenartz requested changes

2023-03-06 17:21 UTC, abenartz commented on lib/providers/signup_login_provider.dart
> +      return isSignupPage ? "Signed up" : 'Signed in';
You actually don't care if it Signed up or Signed in. You can just return "Logged in successfully"

2023-03-06 17:21 UTC, abenartz commented on lib/providers/signup_login_provider.dart
> +  Future<String> getMessageFromFirebaseAuth({
You actually trying to login/signup. This should be your function name.

2023-03-06 17:21 UTC, abenartz commented on lib/providers/signup_login_provider.dart
> +  set updateEmail(String newEmail) {
Are you using all this setter? If not, you can remove them

2023-03-06 17:21 UTC, abenartz commented on lib/providers/signup_login_provider.dart
> +    final Response firebaseAuthResponse = await (isSignupPage
This should be at the authRepository file to handle.

2023-03-06 17:21 UTC, abenartz commented on lib/providers/signup_login_provider.dart
>      notifyListeners();
Why Do we need to notify for the UI on this change. Lets talk about it tomorrow

2023-03-06 18:35 UTC, nitzanpap commented on lib/widgets/signup_login_form.dart
> +                  text: signupLoginProvider.isSignupPage
@abenartz Done.

2023-03-06 18:36 UTC, nitzanpap commented on lib/widgets/signup_login_form.dart
> +            text: signupLoginProvider.isSignupPage
@abenartz Done.

2023-03-06 18:36 UTC, nitzanpap commented on lib/providers/signup_login_provider.dart
> +      return isSignupPage ? "Signed up" : 'Signed in';
@abenartz Done.

2023-03-06 18:36 UTC, nitzanpap commented on lib/providers/signup_login_provider.dart
> +  Future<String> getMessageFromFirebaseAuth({
@abenartz Done.

2023-03-06 18:38 UTC, nitzanpap commented on lib/providers/signup_login_provider.dart
> +  set updateEmail(String newEmail) {
@abenartz I am using these setters. Using them I was able to remove responsibilities from the Stateful form widget (View), and move them into the provider (View Model).

2023-03-06 18:38 UTC, nitzanpap commented on lib/providers/signup_login_provider.dart
> +    final Response firebaseAuthResponse = await (isSignupPage
@abenartz Done.

2023-03-06 18:41 UTC, nitzanpap commented on lib/providers/signup_login_provider.dart
>      notifyListeners();
@abenartz Done.
I see now that notifying the listeners is unnecessary and redundant, since the moment I log in to firebase, I will move into the home page, and any ui elements on the Signup page will be discarded and replaced anyway.

2023-03-08 09:21 UTC, abenartz approved these changes

2023-03-08 09:27 UTC, merged