Task5 user auto authentication
nitzanpap/dispatcher pull request #5
Opened 2023-03-10 19:02 UTC by nitzanpap

2023-03-12 21:30 UTC, abenartz requested changes

2023-03-12 21:30 UTC, abenartz commented on lib/api/firebase/firebase_auth_token_response.dart
> +class User {
Better to separate model classes to different files.
This should be a user under model directory.

2023-03-12 21:30 UTC, abenartz commented on lib/api/firebase/firebase_auth_token_response.dart
> +class ProviderUserInfo {
Same.. Extract to different file

2023-03-12 21:30 UTC, abenartz commented on lib/helpers/helper_functions/device_storage_functions.dart
> +Future<void> saveInPreferencesStorage(
Build class called SharedPreferencesManager.
All these classes should be static function inside him.

2023-03-13 09:37 UTC, nitzanpap commented on lib/api/firebase/firebase_auth_token_response.dart
> +FirebaseAuthTokenResponse firebaseAuthTokenResponseFromJson(String str) =>
@abenartz Done.

2023-03-13 09:37 UTC, nitzanpap commented on lib/api/firebase/firebase_auth_token_response.dart
> +class User {
@abenartz Done.

2023-03-13 09:37 UTC, nitzanpap commented on lib/api/firebase/firebase_auth_token_response.dart
> +class ProviderUserInfo {
@abenartz Done.

2023-03-13 09:38 UTC, nitzanpap commented on lib/helpers/helper_functions/device_storage_functions.dart
> +Future<void> saveInPreferencesStorage(
@abenartz Done in all relevant places.

2023-03-13 12:50 UTC, abenartz approved these changes

2023-03-13 12:54 UTC, merged